title: notes
baseurl: "/notes" # the subpath of your site, e.g. /blog
plugins:
  - jekyll-feed

collections:
  notes:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "_notes"
    values:
      layout: "note"

sass:
  style: compressed

exclude: ["README.md"]
highlighter: rouge

feed:
  path: "posts.xml" # posts do not exist
  collections:
    notes:
      path: "atom.xml"
